// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: nanoid/v1/nanoid.proto

package nanoid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NanoidService_GetTechnology_FullMethodName          = "/nanoid.v1.NanoidService/GetTechnology"
	NanoidService_ListTechnologies_FullMethodName       = "/nanoid.v1.NanoidService/ListTechnologies"
	NanoidService_ListTechnologyVendors_FullMethodName  = "/nanoid.v1.NanoidService/ListTechnologyVendors"
	NanoidService_ListTechnologyCPETypes_FullMethodName = "/nanoid.v1.NanoidService/ListTechnologyCPETypes"
)

// NanoidServiceClient is the client API for NanoidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NanoidServiceClient interface {
	GetTechnology(ctx context.Context, in *GetTechnologyRequest, opts ...grpc.CallOption) (*GetTechnologyResponse, error)
	ListTechnologies(ctx context.Context, in *ListTechnologiesRequest, opts ...grpc.CallOption) (*ListTechnologiesResponse, error)
	ListTechnologyVendors(ctx context.Context, in *ListTechnologyVendorsRequest, opts ...grpc.CallOption) (*ListTechnologyVendorsResponse, error)
	ListTechnologyCPETypes(ctx context.Context, in *ListTechnologyCPETypesRequest, opts ...grpc.CallOption) (*ListTechnologyCPETypesResponse, error)
}

type nanoidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNanoidServiceClient(cc grpc.ClientConnInterface) NanoidServiceClient {
	return &nanoidServiceClient{cc}
}

func (c *nanoidServiceClient) GetTechnology(ctx context.Context, in *GetTechnologyRequest, opts ...grpc.CallOption) (*GetTechnologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTechnologyResponse)
	err := c.cc.Invoke(ctx, NanoidService_GetTechnology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoidServiceClient) ListTechnologies(ctx context.Context, in *ListTechnologiesRequest, opts ...grpc.CallOption) (*ListTechnologiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTechnologiesResponse)
	err := c.cc.Invoke(ctx, NanoidService_ListTechnologies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoidServiceClient) ListTechnologyVendors(ctx context.Context, in *ListTechnologyVendorsRequest, opts ...grpc.CallOption) (*ListTechnologyVendorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTechnologyVendorsResponse)
	err := c.cc.Invoke(ctx, NanoidService_ListTechnologyVendors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nanoidServiceClient) ListTechnologyCPETypes(ctx context.Context, in *ListTechnologyCPETypesRequest, opts ...grpc.CallOption) (*ListTechnologyCPETypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTechnologyCPETypesResponse)
	err := c.cc.Invoke(ctx, NanoidService_ListTechnologyCPETypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NanoidServiceServer is the server API for NanoidService service.
// All implementations must embed UnimplementedNanoidServiceServer
// for forward compatibility.
type NanoidServiceServer interface {
	GetTechnology(context.Context, *GetTechnologyRequest) (*GetTechnologyResponse, error)
	ListTechnologies(context.Context, *ListTechnologiesRequest) (*ListTechnologiesResponse, error)
	ListTechnologyVendors(context.Context, *ListTechnologyVendorsRequest) (*ListTechnologyVendorsResponse, error)
	ListTechnologyCPETypes(context.Context, *ListTechnologyCPETypesRequest) (*ListTechnologyCPETypesResponse, error)
	mustEmbedUnimplementedNanoidServiceServer()
}

// UnimplementedNanoidServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNanoidServiceServer struct{}

func (UnimplementedNanoidServiceServer) GetTechnology(context.Context, *GetTechnologyRequest) (*GetTechnologyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTechnology not implemented")
}
func (UnimplementedNanoidServiceServer) ListTechnologies(context.Context, *ListTechnologiesRequest) (*ListTechnologiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTechnologies not implemented")
}
func (UnimplementedNanoidServiceServer) ListTechnologyVendors(context.Context, *ListTechnologyVendorsRequest) (*ListTechnologyVendorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTechnologyVendors not implemented")
}
func (UnimplementedNanoidServiceServer) ListTechnologyCPETypes(context.Context, *ListTechnologyCPETypesRequest) (*ListTechnologyCPETypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTechnologyCPETypes not implemented")
}
func (UnimplementedNanoidServiceServer) mustEmbedUnimplementedNanoidServiceServer() {}
func (UnimplementedNanoidServiceServer) testEmbeddedByValue()                       {}

// UnsafeNanoidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NanoidServiceServer will
// result in compilation errors.
type UnsafeNanoidServiceServer interface {
	mustEmbedUnimplementedNanoidServiceServer()
}

func RegisterNanoidServiceServer(s grpc.ServiceRegistrar, srv NanoidServiceServer) {
	// If the following call pancis, it indicates UnimplementedNanoidServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NanoidService_ServiceDesc, srv)
}

func _NanoidService_GetTechnology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTechnologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoidServiceServer).GetTechnology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NanoidService_GetTechnology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoidServiceServer).GetTechnology(ctx, req.(*GetTechnologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoidService_ListTechnologies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTechnologiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoidServiceServer).ListTechnologies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NanoidService_ListTechnologies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoidServiceServer).ListTechnologies(ctx, req.(*ListTechnologiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoidService_ListTechnologyVendors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTechnologyVendorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoidServiceServer).ListTechnologyVendors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NanoidService_ListTechnologyVendors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoidServiceServer).ListTechnologyVendors(ctx, req.(*ListTechnologyVendorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NanoidService_ListTechnologyCPETypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTechnologyCPETypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NanoidServiceServer).ListTechnologyCPETypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NanoidService_ListTechnologyCPETypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NanoidServiceServer).ListTechnologyCPETypes(ctx, req.(*ListTechnologyCPETypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NanoidService_ServiceDesc is the grpc.ServiceDesc for NanoidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NanoidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nanoid.v1.NanoidService",
	HandlerType: (*NanoidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTechnology",
			Handler:    _NanoidService_GetTechnology_Handler,
		},
		{
			MethodName: "ListTechnologies",
			Handler:    _NanoidService_ListTechnologies_Handler,
		},
		{
			MethodName: "ListTechnologyVendors",
			Handler:    _NanoidService_ListTechnologyVendors_Handler,
		},
		{
			MethodName: "ListTechnologyCPETypes",
			Handler:    _NanoidService_ListTechnologyCPETypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nanoid/v1/nanoid.proto",
}
