// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        (unknown)
// source: nanoid/v1/rpc.proto

package nanoid

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetTechnologyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTechnologyRequest) Reset() {
	*x = GetTechnologyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTechnologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologyRequest) ProtoMessage() {}

func (x *GetTechnologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologyRequest.ProtoReflect.Descriptor instead.
func (*GetTechnologyRequest) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetTechnologyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTechnologyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Technology *Technology `protobuf:"bytes,1,opt,name=technology,proto3" json:"technology,omitempty"`
}

func (x *GetTechnologyResponse) Reset() {
	*x = GetTechnologyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTechnologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTechnologyResponse) ProtoMessage() {}

func (x *GetTechnologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTechnologyResponse.ProtoReflect.Descriptor instead.
func (*GetTechnologyResponse) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GetTechnologyResponse) GetTechnology() *Technology {
	if x != nil {
		return x.Technology
	}
	return nil
}

type ListTechnologiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpeTypes      []string               `protobuf:"bytes,1,rep,name=cpe_types,json=cpeTypes,proto3" json:"cpe_types,omitempty"`
	Vendors       []string               `protobuf:"bytes,2,rep,name=vendors,proto3" json:"vendors,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	CollectionIds []string               `protobuf:"bytes,4,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
	CreatedFrom   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_from,json=createdFrom,proto3" json:"created_from,omitempty"`
	CreatedTo     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_to,json=createdTo,proto3" json:"created_to,omitempty"`
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	SortBy        string                 `protobuf:"bytes,9,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
}

func (x *ListTechnologiesRequest) Reset() {
	*x = ListTechnologiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechnologiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologiesRequest) ProtoMessage() {}

func (x *ListTechnologiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologiesRequest.ProtoReflect.Descriptor instead.
func (*ListTechnologiesRequest) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ListTechnologiesRequest) GetCpeTypes() []string {
	if x != nil {
		return x.CpeTypes
	}
	return nil
}

func (x *ListTechnologiesRequest) GetVendors() []string {
	if x != nil {
		return x.Vendors
	}
	return nil
}

func (x *ListTechnologiesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListTechnologiesRequest) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

func (x *ListTechnologiesRequest) GetCreatedFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedFrom
	}
	return nil
}

func (x *ListTechnologiesRequest) GetCreatedTo() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTo
	}
	return nil
}

func (x *ListTechnologiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTechnologiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTechnologiesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListTechnologiesRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type ListTechnologiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Technologies []*Technology `protobuf:"bytes,1,rep,name=technologies,proto3" json:"technologies,omitempty"`
	Total        int64         `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Offset       int32         `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit        int32         `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListTechnologiesResponse) Reset() {
	*x = ListTechnologiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechnologiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologiesResponse) ProtoMessage() {}

func (x *ListTechnologiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologiesResponse.ProtoReflect.Descriptor instead.
func (*ListTechnologiesResponse) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ListTechnologiesResponse) GetTechnologies() []*Technology {
	if x != nil {
		return x.Technologies
	}
	return nil
}

func (x *ListTechnologiesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTechnologiesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTechnologiesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTechnologyVendorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectionIds []string `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *ListTechnologyVendorsRequest) Reset() {
	*x = ListTechnologyVendorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechnologyVendorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologyVendorsRequest) ProtoMessage() {}

func (x *ListTechnologyVendorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologyVendorsRequest.ProtoReflect.Descriptor instead.
func (*ListTechnologyVendorsRequest) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ListTechnologyVendorsRequest) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

type ListTechnologyVendorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vendors []string `protobuf:"bytes,1,rep,name=vendors,proto3" json:"vendors,omitempty"`
}

func (x *ListTechnologyVendorsResponse) Reset() {
	*x = ListTechnologyVendorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechnologyVendorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologyVendorsResponse) ProtoMessage() {}

func (x *ListTechnologyVendorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologyVendorsResponse.ProtoReflect.Descriptor instead.
func (*ListTechnologyVendorsResponse) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ListTechnologyVendorsResponse) GetVendors() []string {
	if x != nil {
		return x.Vendors
	}
	return nil
}

type ListTechnologyCPETypesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CollectionIds []string `protobuf:"bytes,1,rep,name=collection_ids,json=collectionIds,proto3" json:"collection_ids,omitempty"`
}

func (x *ListTechnologyCPETypesRequest) Reset() {
	*x = ListTechnologyCPETypesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechnologyCPETypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologyCPETypesRequest) ProtoMessage() {}

func (x *ListTechnologyCPETypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologyCPETypesRequest.ProtoReflect.Descriptor instead.
func (*ListTechnologyCPETypesRequest) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ListTechnologyCPETypesRequest) GetCollectionIds() []string {
	if x != nil {
		return x.CollectionIds
	}
	return nil
}

type ListTechnologyCPETypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpeTypes []string `protobuf:"bytes,1,rep,name=cpe_types,json=cpeTypes,proto3" json:"cpe_types,omitempty"`
}

func (x *ListTechnologyCPETypesResponse) Reset() {
	*x = ListTechnologyCPETypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nanoid_v1_rpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTechnologyCPETypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTechnologyCPETypesResponse) ProtoMessage() {}

func (x *ListTechnologyCPETypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nanoid_v1_rpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTechnologyCPETypesResponse.ProtoReflect.Descriptor instead.
func (*ListTechnologyCPETypesResponse) Descriptor() ([]byte, []int) {
	return file_nanoid_v1_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *ListTechnologyCPETypesResponse) GetCpeTypes() []string {
	if x != nil {
		return x.CpeTypes
	}
	return nil
}

var File_nanoid_v1_rpc_proto protoreflect.FileDescriptor

var file_nanoid_v1_rpc_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x70, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6e, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x76, 0x31,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x15, 0x6e, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f,
	0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a,
	0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x6e, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x63,
	0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x52, 0x0a, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c,
	0x6f, 0x67, 0x79, 0x22, 0xc4, 0x03, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68,
	0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x09, 0x63, 0x70, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x42, 0x0e, 0xfa, 0x42, 0x0b, 0x92, 0x01, 0x08, 0x18, 0x01, 0x22, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x08, 0x63, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x07,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x42, 0x0e, 0xfa,
	0x42, 0x0b, 0x92, 0x01, 0x08, 0x18, 0x01, 0x22, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x76,
	0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x34,
	0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x42, 0x0d, 0xfa, 0x42, 0x0a, 0x92, 0x01, 0x07, 0x22, 0x05,
	0x72, 0x03, 0xb0, 0x01, 0x01, 0x52, 0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x66, 0x72, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x46,
	0x72, 0x6f, 0x6d, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x74,
	0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x6f, 0x12, 0x1f,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x42, 0x09, 0xfa,
	0x42, 0x06, 0x1a, 0x04, 0x18, 0x64, 0x28, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x1f, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x1a, 0x02, 0x28, 0x00, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x62, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x6f, 0x72, 0x74, 0x42, 0x79, 0x12, 0x2f, 0x0a, 0x0a, 0x73, 0x6f, 0x72,
	0x74, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x42, 0x10, 0xfa,
	0x42, 0x0d, 0x72, 0x0b, 0x52, 0x03, 0x61, 0x73, 0x63, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x52,
	0x09, 0x73, 0x6f, 0x72, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x99, 0x01, 0x0a, 0x18, 0x4c,
	0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x74, 0x65, 0x63, 0x68, 0x6e,
	0x6f, 0x6c, 0x6f, 0x67, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6e, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x52, 0x0c, 0x74, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x69,
	0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x54, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65,
	0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x56, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x0d,
	0xfa, 0x42, 0x0a, 0x92, 0x01, 0x07, 0x22, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52, 0x0d, 0x63,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x39, 0x0a, 0x1d,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x56, 0x65,
	0x6e, 0x64, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x22, 0x55, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x43, 0x50, 0x45, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x0e, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x42, 0x0d, 0xfa, 0x42, 0x0a, 0x92, 0x01, 0x07, 0x22, 0x05, 0x72, 0x03, 0xb0, 0x01, 0x01, 0x52,
	0x0d, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x22, 0x3d,
	0x0a, 0x1e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x65, 0x63, 0x68, 0x6e, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x43, 0x50, 0x45, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x70, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x08, 0x63, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x42, 0x32, 0x5a,
	0x30, 0x6d, 0x6b, 0x69, 0x74, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f,
	0x2f, 0x6e, 0x61, 0x6e, 0x6f, 0x69, 0x64, 0x2f, 0x76, 0x31, 0x3b, 0x6e, 0x61, 0x6e, 0x6f, 0x69,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nanoid_v1_rpc_proto_rawDescOnce sync.Once
	file_nanoid_v1_rpc_proto_rawDescData = file_nanoid_v1_rpc_proto_rawDesc
)

func file_nanoid_v1_rpc_proto_rawDescGZIP() []byte {
	file_nanoid_v1_rpc_proto_rawDescOnce.Do(func() {
		file_nanoid_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_nanoid_v1_rpc_proto_rawDescData)
	})
	return file_nanoid_v1_rpc_proto_rawDescData
}

var file_nanoid_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_nanoid_v1_rpc_proto_goTypes = []interface{}{
	(*GetTechnologyRequest)(nil),           // 0: nanoid.v1.GetTechnologyRequest
	(*GetTechnologyResponse)(nil),          // 1: nanoid.v1.GetTechnologyResponse
	(*ListTechnologiesRequest)(nil),        // 2: nanoid.v1.ListTechnologiesRequest
	(*ListTechnologiesResponse)(nil),       // 3: nanoid.v1.ListTechnologiesResponse
	(*ListTechnologyVendorsRequest)(nil),   // 4: nanoid.v1.ListTechnologyVendorsRequest
	(*ListTechnologyVendorsResponse)(nil),  // 5: nanoid.v1.ListTechnologyVendorsResponse
	(*ListTechnologyCPETypesRequest)(nil),  // 6: nanoid.v1.ListTechnologyCPETypesRequest
	(*ListTechnologyCPETypesResponse)(nil), // 7: nanoid.v1.ListTechnologyCPETypesResponse
	(*Technology)(nil),                     // 8: nanoid.v1.Technology
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_nanoid_v1_rpc_proto_depIdxs = []int32{
	8, // 0: nanoid.v1.GetTechnologyResponse.technology:type_name -> nanoid.v1.Technology
	9, // 1: nanoid.v1.ListTechnologiesRequest.created_from:type_name -> google.protobuf.Timestamp
	9, // 2: nanoid.v1.ListTechnologiesRequest.created_to:type_name -> google.protobuf.Timestamp
	8, // 3: nanoid.v1.ListTechnologiesResponse.technologies:type_name -> nanoid.v1.Technology
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nanoid_v1_rpc_proto_init() }
func file_nanoid_v1_rpc_proto_init() {
	if File_nanoid_v1_rpc_proto != nil {
		return
	}
	file_nanoid_v1_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_nanoid_v1_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTechnologyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanoid_v1_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTechnologyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanoid_v1_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechnologiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanoid_v1_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechnologiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanoid_v1_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechnologyVendorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanoid_v1_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechnologyVendorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanoid_v1_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechnologyCPETypesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nanoid_v1_rpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTechnologyCPETypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nanoid_v1_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nanoid_v1_rpc_proto_goTypes,
		DependencyIndexes: file_nanoid_v1_rpc_proto_depIdxs,
		MessageInfos:      file_nanoid_v1_rpc_proto_msgTypes,
	}.Build()
	File_nanoid_v1_rpc_proto = out.File
	file_nanoid_v1_rpc_proto_rawDesc = nil
	file_nanoid_v1_rpc_proto_goTypes = nil
	file_nanoid_v1_rpc_proto_depIdxs = nil
}
